"""Add column name in model Restaurant 

Revision ID: ac27dce34c8f
Revises: c780edc4ea93
Create Date: 2023-05-29 18:31:21.913793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac27dce34c8f'
down_revision = 'c780edc4ea93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'name')
    # ### end Alembic commands ###
